"""
Baseline 4 — LLM-Based Memory Management (Mem0-style).

Uses a large language model, prompted directly, to manage memory at each step.
This mirrors the Mem0 approach: at each new user message, the LLM is asked to
extract, update, and consolidate memory records.

See TODOLIST.md Phase 3, Task 8.

Supports OpenAI-compatible APIs (GPT-4o, Claude via proxy, DeepSeek, etc.).
"""

import json
import os
from typing import List, Optional


MEMORY_MANAGER_SYSTEM_PROMPT = """You are a memory management system for a conversational AI agent. Your job is to maintain an accurate, compact, and useful memory state about the user.

Given:
1. The CURRENT memory state (M) — what the agent currently remembers about the user
2. NEW information (ΔM) — the latest user message or extracted facts

You must produce the UPDATED memory state (M′).

Rules:
- **Update:** If new information contradicts or supersedes an old fact, replace the old fact.
- **Consolidation:** If new information is related to existing facts, merge them into a more compact representation.
- **Abstraction:** If a pattern emerges from multiple facts, add a high-level summary and keep the supporting facts.
- **Forgetting:** If old facts are now obsolete, trivial, or redundant, remove them.
- **Preservation:** Never lose important information. When in doubt, keep it.

Output format: Return ONLY the updated memory state as a bullet-point list. Each bullet should be a self-contained factual statement. Do NOT include any preamble, explanation, or JSON formatting — just the bullet points.

Example CURRENT memory:
- User lives in Hanoi
- User is a software engineer
- User enjoys hiking

Example NEW information:
I moved to Ho Chi Minh City last month for a new job as a senior engineer.

Example UPDATED memory:
- User lives in Ho Chi Minh City (moved from Hanoi last month)
- User is a senior software engineer (recently promoted/changed jobs)
- User enjoys hiking
"""


def _get_llm_client(model: str = "gpt-4o"):
    """Get an OpenAI-compatible client. Set OPENAI_API_KEY and optionally OPENAI_BASE_URL."""
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError("openai package is required. Install with: pip install openai")

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OPENAI_API_KEY environment variable not set.")

    base_url = os.environ.get("OPENAI_BASE_URL", None)
    kwargs = {"api_key": api_key}
    if base_url:
        kwargs["base_url"] = base_url

    return OpenAI(**kwargs)


def transition(
    M: str,
    delta_M: str,
    model: str = "gpt-4o",
    llm_client=None,
    **kwargs,
) -> str:
    """
    LLM-based memory transition: prompt a large model to update memory.

    Args:
        M: Current memory state as a string.
        delta_M: New information to incorporate.
        model: Model name to use (default: gpt-4o).
        llm_client: Optional pre-configured OpenAI client.
        **kwargs: Additional kwargs passed to the API call.

    Returns:
        M_prime: The evolved memory state as generated by the LLM.
    """
    if llm_client is None:
        llm_client = _get_llm_client(model)

    user_prompt = f"CURRENT memory (M):\n{M}\n\nNEW information (ΔM):\n{delta_M}\n\nProduce the UPDATED memory state (M′):"

    response = llm_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": MEMORY_MANAGER_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        temperature=kwargs.get("temperature", 0.3),
        max_tokens=kwargs.get("max_tokens", 2048),
    )

    return response.choices[0].message.content.strip()


def transition_batch(
    memories: List[str],
    deltas: List[str],
    model: str = "gpt-4o",
    llm_client=None,
    **kwargs,
) -> List[str]:
    """Batch version — processes sequentially (LLM calls are serial)."""
    assert len(memories) == len(deltas)
    if llm_client is None:
        llm_client = _get_llm_client(model)

    results = []
    for m, d in zip(memories, deltas):
        result = transition(m, d, model=model, llm_client=llm_client, **kwargs)
        results.append(result)
    return results